### ISSUE TITLE
Domanda sul footer

### ISSUE THREAD

**Issue by Marco-Saini** [DavideBrambilla98/Progetto2_PW24#17]
ho notato che la pagina generata quando clicco il link ha un footer un po' alto
![image](https://github.com/user-attachments/assets/6d3bf0bd-82c3-4f7e-ae8b-0098affbdc5d)
é normale? lo sapete? bisogna sistemarlo?

**Comment by DavideBrambilla98** [comment]
Nel main ho caricato l'ultima versione e dovrebbe essere a posto.
Se non si sistema è perché bisogna cancellare la cache del browser
